- reference/list/splice.md
「2つのコンテナを併合する」というmerge関数と同じ説明から、「他の`list`オブジェクトから、要素を移動する。」というより適当な説明に変更。
> List/splice.md の splice関数の概要を修正

- lang/cpp11/static_initialization_thread_safely.md
`singleton::get_instance()`が参照型`singleton&`を返すよう変更
- 値型だと戻り値でコピーが行われてしまい、（狭義の）シングルトン・パターンからは外れてしまうため変更しました。
s/デッドロック/並行性バグ/
- 誤ったDouble Checked Lockingイディオムによるデッドロックはまず起こりえないと思います。データ競合(data race)のリスクが高いという意味で「並行性バグ」としてみました。
> ブロックスコープを持つstatic変数初期化のスレッドセーフ化 の小さな修正

- lang/cpp11/rvalue_ref_and_move_semantics.md
式`std::move(x)`の評価結果を右辺値参照型(`T&&`)変数に束縛する行為それ自体は、元オブジェクト`x`に何の変化も生じず「ムーブ」とは呼べない。あわせて`int`などのスカラ型ではムーブ操作の意義がないため、例示コードで対象とする型を`std::string`に変更。
> ムーブセマンティクス説明文＋例示コードの調整

- implementation.md
Visual C++ Build Toolsへのリンクがブログへのリンクになっていて
分かりづらかったので、ダウンロードページにURLを変更しました。
> Visual C++ Build Toolsへのリンクをブログから公式ページヘ変更

- reference/algorithm.md
algorithm.mdにincludes.mdへのリンクがなかったため追加しました。
追加する位置が集合演算のテーブルで良いのか不安なためPRにさせていただきました。
参考: cppreference.comやcplusplus.comではmerge, inplace_merge, includes, set_* が1つのテーブルにまとまっているようでした
> includesへのリンクがなかったので修正

- implementation-status.md
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/n4586.pdf
> **Motion 2** Move to direct the convener to inform SC22 we will not produce an Arrays TS and close
the Arrays TS work item.
> [...]
> Approved by unanimous consent.
> Array Extensions TSの取り下げに伴い該当記述を削除

- lang/cpp11.md
finalの概要説明部分で、オーバーライドであるべき部分がオーバーロードと表記されていた箇所を修正しました。
> fixed probable mistake in the description of final

- reference/vector/op_at.md
array::operator[ ] と同様に説明文中の `begin()` が `vector::begin` へのリンクとなるよう変更しました。
> vector::operator[ ] : vector::begin()へのリンク忘れを修正

- reference/string/char_traits/compare.md
規格(参考にしたのはドラフトのN3337とN4296ですが)によると `linear` とのことだったので、変更しました。
> std::char_traits::compare 定数時間 から 線形時間 に変更

- lang/cpp11/thread_local_storage.md
N4296の7.1.1 Storage class specifiersには，
> At most one storage-class-specifier shall appear in a given decl-specifier-seq, except that thread_local may appear with static or extern.
とあり，cppreferenceなどにも，
> Only one storage class specifier may appear in a declaration except that thread_local may be combined with static or with extern (since C++11)
とあることから，修正前の仕様説明はミスであると考えられるため，修正しました．
http://en.cppreference.com/w/cpp/language/storage_duration
> thread_localの説明を修正

- lang/cpp11/range_based_for.md
概要で挙げられているコード例ではfor (const auto& e : v)ですが、
"従って概要で挙げた例は以下のように展開される"という部分のコード例ではconstの記述がなかったため修正.
> 展開後のコード例の変更

- reference/concepts/Callable.md
- reference/concepts/CopyAssignable.md
- reference/concepts/CopyConstructible.md
- reference/concepts/DefaultConstructible.md
- reference/concepts/Destructible.md
- reference/concepts/EqualityComparable.md
- reference/concepts/Invoke.md
- reference/concepts/LessThanComparable.md
- reference/concepts/MoveAssignable.md
- reference/concepts/MoveConstructible.md
- reference/concepts/Swappable.md
- reference/concepts/ValueSwappable.md
- reference/container_concepts/CopyInsertable.md
- reference/container_concepts/EmplaceConstructible.md
- reference/container_concepts/MoveInsertable.md
ref: #469 https://github.com/cpprefjp/site/issues/469#issuecomment-326191629
>> タイトルで std::Callable とすべきではないと思います．
> これはミスなので、見つけたら適時直してください。
直しました。
ジェネレータのソースコードを読んでみましたが、 meta が無ければヘッダの文字列がそのまま使われるので、単純に削除して大丈夫だと思います。
https://github.com/cpprefjp/markdown_to_html/blob/e8bdbadd6e2838c8bd1ce377316a915cc6bcad08/meta.py#L133
> コンセプトから meta namespace を削除

- index.md
アナリティクス利用規約の第7項「プライバシー」では、サイト内でアナリティクスを利用する際にプライバシーポリシーを示さなければならないとされています。この目的のため、現状を簡潔に説明したポリシーを新しくトップページに表記します。
https://www.google.com/analytics/terms/jp.html
>  Google Analyticsのポリシーを表記

- reference/algorithm/minmax.md
qiitaにて、std::minmax()の落とし穴について投稿いたしました。
https://qiita.com/sumomoneko/items/58358eb8bcc8b70a481b
実際にminmax()を使う際に参照されることが多いであろうこのサイトにて、
注意喚起があって良いのではと思い、またyumetodoさんの後押しもあって
備考を追記しました。
下記議論を参照し、サンプルコードの拡張記法にも対応させています。
https://github.com/cpprefjp/site/issues/481
最適化の具合により、assert()で問題が出たり出なかったりします。
> minmaxの注記に、ダングリングが発生するケースを追加

- reference/ostream/basic_ostream/put.md
[basic_ostream::put](https://cpprefjp.github.io/reference/ostream/basic_ostream/put.html) の記事にて
`write`のシグネチャが紹介されているため,`put`のシグネチャに差し替え.
簡単な修正ですが、push権限がないのでPull-requestを送信いたします。
ご精査のほどよろしくお願いいたします。
> basic_ostream::put の関数シグネチャの修正

- reference/string/to_string.md
`std::to_string()` のサンプル実装の修正です.
- `std::numeric_limits<T>::digits10` 及び `max_exponent10` の値は実際の最大桁数 *-1* になるため, バッファサイズは現状より1バイトだけ多いものが必要です.
- バッファの変数名に `buffer` と `buff` が使われていましたが, 特に分ける理由もなさそうに見えたので `buffer` に統一しました.
- コメント中の `NULL` を `'\0'` に変更しました.
> Fix sample implementations of std::to_string().

- reference/random/mt19937.md
ページ移転によりドメインが変更されたようです。
http://homepage1.nifty.com/herumi/diary/1505.html#18
↓
http://herumi.in.coocan.jp/diary/1505.html#18
> [std:: mt19937] 項目：予測可能性に記載された参照先のリンク切れを修正します

- implementation.md
バージョン表記が「14.0 Update 3」「15.3」と揺れがあったので統一した。
製品名、Visual C++ バージョンも不完全な部分を修正した。
言語機能の切り替えについても補足しつつ修正した。
> MSVCのバージョン表記を統一

- reference/string/to_wstring.md
[to_wstring](https://cpprefjp.github.io/reference/string/to_wstring.html) の戻り値の型がstringになっていますが、wstringが正しいと思うので修正してみました。
> to_wstringの戻り値の型を修正

- reference/optional/optional/op_greater.md
- reference/optional/optional/op_greater_equal.md
std::optionalの比較演算`>`と`>=`の説明のタイポを修正しました
> std::optionalの比較演算子のタイポ修正

- reference/algorithm/clamp.md
> clampの引数順序の修正

- reference/optional/optional.md
原文は "A program that necessitates the instantiation of template optional for a reference type, or for possibly cv-qualified types in_place_t or nullopt_t is ill-formed" です。"possibly cv-qualified" は `in_place_t` と `nullopt_t` に掛かっているはずなので、その部分を修正しました。
> optional クラステンプレートの要件を修正

- implementation-status.md
- lang/cpp17/dynamic_memory_allocation_for_over-aligned_data.md
言語機能一覧にページを作っていたなかったため、作成しました。
それに伴って、implementation-statusからのリンク先を変更しました。
> アライメント指定されたデータの動的メモリ確保

- lang/cpp17/nested_namespace.md
> サンプルコードの脱字修正 (C++17 入れ子名前空間)

- reference/any/any/op_assign.md
std::decay_t<T>とstd::anyを取り違えているような文脈だったので、修正しました。
> any::operator=の効果を修正

- lang/cpp17/if_constexpr.md
参照です
[Qiita](https://qiita.com/alphya/items/b3463d1a2f53687f6025)
[teratail](https://teratail.com/questions/166409)
> update(if constexpr): ラムダを使った方法の追加

- reference/utility/pair/get.md
tupleは追記されていましたが、pairは無いようなので追記しました。
ご査収ください。
> std::pairに対する要素型を指定するstd::getのオーバーロードの追記

- reference/numeric/reduce.md
- 2項演算の適用が順不同であることを強調
- 2項演算に関する"非可換(non-commutative)"性を削除
- 仕様上は非決定的な結果となるstd::stringリスト簡約例を削除
> reduce: 簡約過程の演算順序が未規定であることを反映

- reference/limits/numeric_limits/is_bounded.md
- modified: `reference/limits/numeric_limits/is_bounded.md`
訳語表と相違していたため, `std::numeric_limits::is_bounded` について
_fundamental types_ の訳を「基本型」から「単純型」に変更した.
> is_bounded 表記ゆれを修正

- lang/cpp20/modules.md
Githubではレンダリングできるが、cpprefjpのレンダラーでは空行が必要
> 連続するコードブロックの間に空行を追加

- reference/thread/this_thread/sleep_for.md
- reference/thread/this_thread/sleep_until.md
`this_thread::sleep_*()` のサンプルコードで `chrono` ヘッダのインクルードをし忘れていることに気付いたので修正しました
> thread: サンプルコードでの include し忘れを修正

- reference/string/basic_string/find.md
- reference/string/basic_string/find_first_not_of.md
- reference/string/basic_string/find_first_of.md
- reference/string/basic_string/find_last_not_of.md
- reference/string/basic_string/find_last_of.md
- reference/string/basic_string/op_equal.md
- reference/string/basic_string/op_greater.md
- reference/string/basic_string/op_greater_equal.md
- reference/string/basic_string/op_less.md
- reference/string/basic_string/op_less_equal.md
- reference/string/basic_string/op_not_equal.md
- reference/string/basic_string/rfind.md
basic_stringのリファレンスに対し、次の修正をしました。
次のメンバ関数において引数に `charT` 型をとるものから「C++11」という補足を削除しました。
* find
* find_first_not_of
* find_first_of
* find_last_not_of
* find_last_of
* rfind
`charT` 型を引数にとるメンバ関数はC++03の頃から存在していると思うからです。
「C++11」という記述は 85da2ec23c49e72dcc133acfed6a430be4591a44 において追加されていましたが、その意図はよくわかりませんでした。
basic_string同士の `==` 演算子と `!=` 演算子の対応バージョンを「C++11」から「C++03」に変更しました。
理由はfind系メンバ関数に対する変更と同じです。
basic_string同士の演算子 `>`, `>=`, `<=`, `<` には `noexcept` 版の記述がなかったので、 `==` 演算子と同等の記述を追加してみました。
basic_string同士の比較演算子の `noexcept` 版の対応バージョンは「C++14」になっています（`==` がそうなっていたので `>=` なども今回それに合わせました）。
ですが、N3337 を見るとC++11でもnoexceptが付いているように思えました。
* https://timsong-cpp.github.io/cppwp/n3337/string::operator==
なので当該演算子で今C++14と書いている所はC++11と書くのが正しいような気がします。ただ、cppreference.comやcplusplus.comでもnoexceptはC++14から付くような記述になっ …
> basic_stringのfind系メンバ関数と比較演算子の対応バージョンを修正

- lang/cpp14.md
C++14ページの見出しに、間違いと思われる箇所があったので修正しました。
「メモリ管理」の節は「ライブラリ更新の概要」の下だと思うので修正しています。
> 見出しの間違いを修正

- lang/cpp17/if_constexpr.md
間違っているとは言い切れないが、この例だけシグネチャが違うのでミスである可能性が高いと判断。
> C++17 constexpr if : 2段階名前探索における注意点、関数のシグネチャを修正

- reference/algorithm/move_backward.md
> std::move_backward: サンプルのコメントミス修正

- lang/cpp17.md
https://cpprefjp.github.io/lang/cpp17.html
をブラウザで開いているときに、ページ内検索でinlineをキーワードにしたときに、インライン変数が引っかからないのが不便な気がするので説明に含めてみました。
すくなくとも自分は過去4回くらいあれ、引っかからないぞとなって探し回った経験があるので提案します。
> ページ内検索でinlineをキーワードにしたときに、インライン変数が引っかからないのが不便な気がするので説明に含める

- reference.md
- reference/stop_token.md
- reference/stop_token/nostopstate.md
- reference/stop_token/stop_callback.md
- reference/stop_token/stop_source.md
- reference/stop_token/stop_token.md
- working_style.md
タイトルの通り、 stop_token ヘッダと関連クラスの概要を追加しました。
なので、メンバ関数のリファレンスはTODO状態です。
初めての執筆で具合が分からないですが、なるべく他の記事や editors_doc の記載を参照して書きました。こんな感じで大丈夫でしょうか？
よろしくお願いしますー
> stop_token ヘッダと関連クラスの概要を追加

- .github/workflows/build.yml
- .github/workflows/script/build.sh
今まで自分が管理してたさくらVPSのサーバを使ってビルドしていましたが、それを GitHub Actions で行うようにしました。
- site の master ブランチへの push か、毎日 23:30 をトリガーにビルドが走ります。
- デイリーを用意しているのは site_generator や kunai が更新された時に反映する用です。
- サイトをビルドした後、cpprefjp/cpprefjp.github.io に自動的に push します。
- cpprefjp.github.io に push するための秘密鍵は GitHub の Secrets に保存していて、公開鍵は cpprefjp.github.io のデプロイキーとして登録しています。
- 秘密鍵は手元でも削除したので、もし何かの理由で使えなくなったら登録し直す必要があります。
> サイトのビルドを GitHub Actions 化した

- reference/memory/shared_ptr/swap.md
- reference/memory/shared_ptr/swap_free.md
- reference/memory/unique_ptr/swap.md
- reference/memory/unique_ptr/swap_free.md
- reference/memory/weak_ptr/swap.md
- reference/memory/weak_ptr/swap_free.md
現状の例だと「値が交換されている」ことを確かめているように見えるので、ポインタ自体の値を出力することで、「ポインタが交換されている」ことが明確になるかと思います。
出力が実行毎に変わってしまいますが、[shared_ptr::operator<<](https://github.com/cpprefjp/site/blob/5b2e17205cdeaf56b0deb677e73674c613043fae/reference/memory/shared_ptr/op_ostream.md#%E5%87%BA%E5%8A%9B%E4%BE%8B)などが「出力例」として出しているので、それに習って「例」にも変更しています。
> スマートポインタのswapで、ポインタが入れ替わることが明確になる例にした

- reference/mutex/unique_lock.md
`std::condition_variable` の `std::` がバッククオートされていなかったので追加しました。
よろしくお願いします。
> Fix unique_lock.md where 'std::' is not backquoted

- .gitattributes
- .github/workflows/outer_link_check.yml
- .github/workflows/script/create_github_issue_when_not_empty.sh
#749 にGithub Issueを作る機能を追加する。
shell scriptが動くのは確認しているが、Github Actions側の変数回り(` ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} ${{ github.sha }}`)は
https://help.github.com/ja/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#example-calling-the-rest-api
を見ただけなので確証はない。
> feat(ci): create issue when outerlink check detect outdated

- reference/iostream/cout.md
- wchar_t型がUnicodeであるとは限らないため、「`wcout`自体はUnicodeを扱うが」という表現を避ける。
- 描画側について整理
- Windows Terminalが正式リリースではないものの[Microsoft Store](https://www.microsoft.com/ja-jp/p/windows-terminal-preview/9n0dx20hk701?ranMID=24542&ranEAID=TnL5HPStwNw&ranSiteID=TnL5HPStwNw-UDWMLG8.vwB2U4dqg2Flhw&epi=TnL5HPStwNw-UDWMLG8.vwB2U4dqg2Flhw&irgwc=1&OCID=AID681541_aff_7593_1243925&tduid=%28ir__zlyl9dwgqkkfr3dlkk0sohzx0m2xj1uvbfrd6e0v00%29%287593%29%281243925%29%28TnL5HPStwNw-UDWMLG8.vwB2U4dqg2Flhw%29%28%29&irclickid=_zlyl9dwgqkkfr3dlkk0sohzx0m2xj1uvbfrd6e0v00&activetab=pivot%3Aoverviewtab)で公開されて暫く経つため言及
- deef1b095e731268ac4af26099f15be3c0de000b で書いたCロケールになるバグの出典が探せない上に再現できないので除去
- MinGW環境での`locale::facet::_S_create_c_locale name not valid`は`std::locale("")`でも発生するので修正
ref:
- #560
> fix(wide-io): wchar_t型がUnicodeであるとは限らないため避ける。また描画側についての記述を追記

- reference/cmath.md
以下に示すstd::numeric_limitsの静的メンバ定数が，誤って静的メンバ関数として扱われているようだったため，修正しました．
* std::numeric_limits<T>::has_infinity
* std::numeric_limits<T>::has_quiet_NaN
> fix: cmathのページにおけるエラーの種類に関する項目の説明の修正

- reference/cmath/abs.md
修正前表現ではabs関数そのものが廃止されると誤解されるリスクがあった。
> abs: C++17で行われた対処を明確に記述

- reference/type_traits/is_array.md
たぶんどこかからコピペしてきた際に消し忘れたっぽい `double` を削除しました．
> static_assertの説明文を修正

- .github/workflows/outer_link_check.yml
https://docs.github.com/ja/actions/reference/events-that-trigger-workflows#scheduled-events
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
外部リンクチェックがときどき、相手側サーバーが落ちているのかなにかが原因でちょくちょく失敗するので、週に一回実行するようにしてみました。ほんとは「連続N日間失敗したら…」とかにするのがよさそうですが。
日曜日の23:30に実行するようにしてみたのですが、これで合ってますかね。
どなたかに確認していただきたいです。
> 外部リンクチェックを週に一回チェックするようにした

- reference/iterator/istream_iterator.md
一応全てのファイルが最初にC++のソースコードを表示しているという前提で`grep "```" -m 1`で調べてみましたが、他は大丈夫そうです（真ん中にあるブロックは見ていませんが）。
> コードブロックに抜けているcppを追加

- reference/exception.md
飛び先の冒頭の表現に揃えます:
https://github.com/cpprefjp/site/blob/719664d66832cb1674c283967486cca5cf2d9f92/reference/exception/bad_exception.md#%E6%A6%82%E8%A6%81
> `bad_exception` クラスは、関数に対して例外の型を制限し、指定外の **型** を送出した場合に発生する例外である。
C++11以降を考えると、ここは全体をrewordした方が良いかもしれません。が、ちょっと良い表現が思いつきませんでした。。
```
関数で例外の型を制限し、指定外の型が送出された場合に発生する例外クラス(C++11以前)
または、std::current_exceptionの失敗を表現する例外クラス(C++11以降)
```
> bad_exception のサマリのtypo 方 -> 型

- lang/cpp20.md
- reference/memory/allocator_traits.md
@wx257osn2  複数の問題を解決するPRを作るな
- C++20の言語機能のページのtypoを3件修正
- `allocator_traits` のコードハイライトの範囲を修正
- `allocator_traits::rebind_alloc` の `Args` についての説明を追加
> typoの修正と文面の追加

- reference/type_traits/is_abstract.md
- reference/type_traits/is_const.md
- reference/type_traits/is_empty.md
- reference/type_traits/is_pod.md
- reference/type_traits/is_polymorphic.md
- reference/type_traits/is_signed.md
- reference/type_traits/is_trivial.md
- reference/type_traits/is_unsigned.md
- reference/type_traits/is_volatile.md
気づいたので直しましたが、この部分には`value == (true|false)`を含まないようにしているページもあるようなので、単に消すだけでも良かったかもしれません。
> static_assertのメッセージにあるtypoの修正

- reference/fstream/basic_ifstream.md
- reference/fstream/basic_ofstream.md
basic_ifstream と basic_ofstream の基本クラスを修正しました。
修正前
class basic_ifstream : public basic_iostream<charT,traits> {
class basic_ofstream : public basic_iostream<charT,traits> {
修正後
class basic_ifstream : public basic_istream<charT,traits> {
class basic_ofstream : public basic_ostream<charT,traits> {
C++11
27.9.1.6 Class template basic_ifstream
namespace std {
template <class charT, class traits = char_traits<charT> >
class basic_ifstream : public basic_istream<charT,traits> {
...
};
27.9.1.10 Class template basic_ofstream [ofstream]
namespace std {
template <class charT, class traits = char_traits<charT> >
class basic_ofstream : public basic_ostream<charT,traits> {
...
};
C++14
27.9.1.6 Class template basic_ifstream
namespace std {
template <class charT, class traits = char_traits<charT> > …
> Fixed mistakes in ifstream and ofstream base class

- reference/ostream/ends.md
初めまして。
KodaiYMと申します。いつもこちらのサイトでお世話になってます。
std::ends のページの実装例で、関数名が「endl」と誤記されていて気になったので、
(pull request の練習も兼ねて)ends に修正しました。
よろしくお願いします。
> std::ends の実装例の誤記 endl を ends に修正

- implementation-status.md
typoかと思われる項目ありましたのでPR出します〜
「暗黙のラムダキャプチャを簡素化」の項目のMSVCの対応バージョンのtypo
参考：https://docs.microsoft.com/ja-jp/cpp/overview/visual-cpp-language-conformance?view=msvc-160
P0409R2 Allowing lambda-capture [=, this] | VS 2019 16.2 20
> Fixed typo msvc version (暗黙のラムダキャプチャを簡略化)

- lang/cpp20/concepts.md
autoパラメータの説明の例示コードについて、コメント中の `f` の第2引数の `T` は `U` の誤記だと思います。
> concepts: 例示コードの型のtypoを修正

- lang/cpp20/char8_t.md
C++20言語機能「UTF-8エンコーディングされた文字の型としてchar8_tを追加」の参照リンクにもれがあるので追記しました
Document Number: | P0482R6
char8_t: A type for UTF-8 characters and strings (Revision 6)
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0482r6.html
> Added link [P0482R6] (C++20:UTF-8エンコーディングされた文字の型としてchar8_tを追加)

- implementation-status.md
コンパイラの実装状況について、記載漏れと思われる項目を更新しました　　
FYI: https://docs.microsoft.com/ja-jp/cpp/overview/visual-cpp-language-conformance
- 評価されない文脈でのラムダ式 
- VS2019 update 8
- P0315R4 Allowing lambdas in unevaluated contexts
- 範囲for文がカスタマイゼーションポイントを見つけるルールを緩和
- VS2019 update 5
-  P0962R1 Relaxing the range-for loop customization point finding rules
- 抽象型のチェック 
- VS2019 update 5
- P0929R2 Checking for abstract class types
- 可変長データを扱うクラスの効率的な`delete` 
- VS2019 update 7
-  P0722R3 Efficient sized delete for variable sized classes
よろしくお願いします
> コンパイラの実装状況にMSVCの更新情報を追加

- implementation-status.md
コンパイラの実装状況について、追記と記載ミスと思われる項目を更新しました
References: https://docs.microsoft.com/ja-jp/cpp/overview/visual-cpp-language-conformance
- 構造化束縛した変数の参照キャプチャを許可
- 2017 Update 3
-  P1381R1 Reference capture of structured bindings
- 丸カッコの値リストからの集成体初期化を許可
- 2019 Update 8
-  P0960R3 Allow initializing aggregates from a parenthesized list of values
- `new`式での配列要素数の推論
- 2017 Update 7
-   P1009R2 Array size deduction in new-expressions
- モジュール
- 2019 Update 8
-  P1103R3 Modules
- コルーチン
- 2019 Update 8
-   P0912R5 Coroutines
- 添字演算子内でのカンマ演算子の使用を非推奨化
- 2019 Update 5
-   P1161R3 Deprecate uses of the comma operator in subscripting expressions
- constexprの文脈でのトリビアルなデフォルト初期化を許可
- 2019 Update 7
-   P1331R2 Permitting trivial default initialization in constexpr contexts
- 集成体クラステンプレートのテンプレート引数推論
- 2019 Update 7 …
> コンパイラの実装状況にMSVCの更新情報/Clang typo修正を追加

- third_party_library.md
公式版にリンク先差し替え。（非公式）日本語サイトへのリンクを旧バージョンの日本語マニュアルとして変更。ライセンスを（三条項）BSDからApache 2 Licenseに変更。
> OpenCVのリンク先とライセンス修正

- reference/tuple/tuple/op_less.md
> tupleのoperator<の説明をC++17に沿ったものに修正

- reference/algorithm/sort.md
1. C++11/C++20のコード例にalgorithmヘッダを追加
2. C++11のコード例にexampleタグを追加 (C++20のコード例にはexampleタグは付与せず)
std::sortのC++11/C++20のコードサンプルを実行してみると、
コンパイルエラーとなり、ヘッダが漏れていることに気が付きました。
C++11の方はブラウザ上で実行できるかと思うので、
タグも付けておきました。
> std::sortのサンプル修正

- reference/algorithm/max_element.md
- reference/algorithm/min_element.md
comp argument of std::min_element expects the function that takes (a, b) and return true if a < b.
Of course, a > b is also valid (compilable), but it might be not appropriate for an example.
> fix the direction of comparison in the example

- reference/type_traits/alignment_of.md
- reference/type_traits/extent.md
- reference/type_traits/rank.md
std::alignment_of, std::extent, std::rank の各クラスが、std::integral_constantから派生していることについて記載がなかったので、「備考」として追記しました。
> add comments regarding std::integral_constant

- reference/concepts/copyable.md
- reference/concepts/regular.md
- reference/concepts/semiregular.md
元の文面だと同格修飾のようにも読めるため、前提条件であることが明らかになるように修正しました。
本プルリクエストに関連して、以下のことについてコメントをいただきたいです：
* [`movable`](https://cpprefjp.github.io/reference/concepts/movable.html)のページにある「必然的にswap可能であることを表す」の意味が分かりづらいと思うが、意図が不明で修正できなかった
* 文章のどの部分から、どのような論理で、導かれるのかがよくわかりませんでした
* 導かれるのであれば、文を分けて理由付きで説明したほうがよさそうです
* わざわざコンセプトの条件に記載されているということは、特殊な条件下では満たされない、つまり「必然」ではないという可能性を示唆しているように思います
* P0898R3に記載されている There need be no subsumption relationship between Movable<T> and is_object_v<T>. と関係があるのでしょうか
> 値指向なコンセプトの説明文面を修正

- reference/fstream/basic_filebuf/open.md
テーブルの `ate` を `app` に修正します。
規格書は確認しておらず、 https://en.cppreference.com/w/cpp/io/basic_filebuf/open との比較によります。
> basic_filebuf::open: fix openmode table

- reference/queue/priority_queue.md
以下を修正しました。typo のようです。
* `priority_queue` とすべきところを `queue` となっている点を修正
* `priority_queue` のテンプレート引数は、2つではなく3つなので文言修正(その後の説明でも3つ分説明がある)
> Fix typo in priority_queue description

- reference/algorithm.md
規格書は確認していない。
https://cpprefjp.github.io/reference/algorithm/lexicographical_compare_three_way.html が C++20 と書かれている点と三方比較自体が、 C++20 からであるため正しいと考えている。
> algorithm.md: lexicographical_compare_three_way は C++20 から

- reference/concepts/movable.md
`movable`コンセプト定義が`swappable`コンセプトを含む理由文を補強・調整してみました。論旨は変えていないつもりです。
関連Issue #929
> movable: 制約式にswappableを含む理由説明の調整

- reference/algorithm.md
- reference/array/array/crend.md
- reference/forward_list/forward_list.md
- reference/forward_list/forward_list/cbefore_begin.md
- reference/vector/vector/crend.md
std::forward_list::cbefore_begin について、ファイル名とタイトルが間違っていたので修正しました。
他に細かな修正を３点行っています。
> rename before_cbegin.md to cbefore_begin.md.

- reference/atomic/atomic/op_minus_assign.md
- reference/bitset/bitset/op_constructor.md
- reference/memory/shared_ptr/op_less.md
- reference/memory/unique_ptr/op_less.md
atomicのoperator-=：-を+に間違えていたので修正。
bitsetのconstructor：(4)の例外条件が抜けていたので追加。
unique_ptrとshared_ptrのoperator<：`が足りていない箇所があったので追加。
> fix some typos

- reference/string_view/basic_string_view/op_constructor.md
https://github.com/cpprefjp/site/blob/c979c55860c923d0090b0e1c0b3299c2e99e299c/reference/string_view/basic_string_view/op_constructor.md?plain=1#L45
`traits_type` が `type_traits` になっている部分がありましたので、修正しました。
> Fix typo in basic_string_view/op_constructor

- reference/span/span/op_constructor.md
https://github.com/cpprefjp/site/blob/a3087226e6295ad8c0068e0e101b2f2b9fc1a6c6/reference/span/span/op_constructor.md?plain=1#L106
- `safe_range` は `borrowed_range` の誤りだと思うのですが、いかがでしょうか。
- *Reference: [[span.cons]](https://timsong-cpp.github.io/cppwp/n4861/views#span.cons-15.3)*
> Fix typo in span/op_constructor

- reference/type_traits/has_virtual_destructor.md
使い所がわからない，という声を聞いたのでそれっぽい用例を追記してみました
> std::has_virtual_destructorの使用例を追加

- reference/functional/bad_function_call.md
- reference/memory/bad_weak_ptr.md
gcc 4.7.2のstd::bad_weak_ptrのwhat()が規格違反だった件について、十分時間が経っているので、バージョン内の記載のみに変更。
std::bad_function_callはそもそもstd::bad_weak_ptrと無関係のはず。
> update commentary of std::bad_weak_ptr gcc supports

- reference/iterator/ssize.md
- reference/ranges/ssize.md
コメントの内容がミスリーディングかな、と思えました。ptrdiff_tについてssize()のサンプルで言及する必要もないので、削除するのが良いと考えました。
> remove unnecessary comment in samples

- reference/random/piecewise_constant_distribution.md
`random/piecewise_constant_distribution.md`にて，`min`が`mix`と誤記されているのを見つけたので修正しました
[C++ draft](http://eel.is/c++draft/rand.dist.samp.pconst#:~:text=result_type%20min()%20const%3B)
> fix typo in random/piecewise_constant_distribution.md

- reference/ranges/all.md
- reference/ranges/owning_view.md
- reference/ranges/view.md
- reference/ranges/viewable_range.md
[P2415R2 What is a `view`?](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2415r2.html) の内容の中で、未執筆のものを記述しました。
- `viewable_range` コンセプトを修正しました。この際 [LWG Issue 3481 `viewable_range` mishandles lvalue move-only views](https://cplusplus.github.io/LWG/lwg-defects.html#3481) も参考文献に付与しました
- 関係するページの参考文献にP2415R2を追加しました。この際「本論文はC++20に遡って適用されている」ことを明記しました
@tetsurom 私がタイポ以外の変更を加えるのは今回が初めてになります。差し支えございませんでしたら、スタイル等についてレビューをお願いできますでしょうか。
> P2415R2 What is a view?に対応

- reference/concepts/totally_ordered.md
`totally_ordered`の方にもテンプレート引数`U`があったので、消しました。
> 本来存在しないテンプレート引数を削除

- reference/variant/variant/emplace.md
- reference/variant/variant/op_assign.md
- reference/variant/variant/op_constructor.md
- reference/variant/variant/op_destructor.md
- reference/variant/variant/swap.md
- reference/variant/variant/swap_free.md
- DR LWG 2901によってアロケータサポートが削除されたのを反映
- という歴史的経緯は記載したほうが良い？現行は単に削除してあります
- ~~C++17では代入演算子はtrivialにならないっぽいのでC++20以降であることを明記~~ これは嘘
- `constexpr` が ~~付いてないとこについてたりC++20/~~ 23以降付くやつ ~~とか~~ があったので適宜 ~~修正~~ **追加**
- C++20以降付くのではなくC++17に対するDRとして付いたので元の記述が正しい
> variant関連の修正

- reference/functional/bind.md
`std::bind`でメンバー関数をbindするのは頻出イデオムですがそういえば例に無いので足してもいいのではないかと思いました。
> feat: std::bindでメンバー関数を呼び出す方法を例に追加

- reference/shared_mutex/shared_timed_mutex.md
typoの修正です。文章中のTryCodeでもコンパイルエラーが起きないことを確認しました。
> typo/コンパイルエラーの修正: shared_mutex→shared_timed_mutex

- start_editing/directory_structure.md
https://github.com/cpprefjp/site/issues/1066#issuecomment-1417098816
expected と expected.void を特例として明記しました。
> ディレクトリ構造: クラス階層expected/expected.void特例を明記

- lang/cpp17/guaranteed_copy_elision.md
最適化されない場合はコピーコントラクタの前にムーブコンストラクタを優先して実行しようとすると思います。
参考：
https://timsong-cpp.github.io/cppwp/n4861/class.copy.elision#3
ページに書かれている引用元も「最適化が無効な場合は、ムーブコンストラクタが呼ばれます。」となっていたため誤字と判断しました。（引用元のコードが変更された...？）
https://ja.cppreference.com/w/cpp/language/copy_elision
以上、ご確認よろしくお願い致します。
> guaranteed_copy_elision.md にて、ムーブコントラクタが呼ばれるはずのところがコピーコントラクタが呼ばれると記載されていたため修正

- reference/limits/numeric_limits/digits.md
- reference/limits/numeric_limits/max_exponent.md
- reference/limits/numeric_limits/min_exponent.md
{max,min}_exponentは単に指数の最大値・最小値と誤解されがちですが、サンプルコード出力から推測されるとおりここから1引いた値が指数の最大値・最小値となります。（仕様の[numeric.limits.members]にも`one less than that integer`と明記されている）
なお同様のマクロがあるcfloatの説明文では1を引くことが既に書かれていました。
> numeric_limits: リンク切れおよび{max,min}_exponentの説明間違いの修正

- lang/cpp17/type_deduction_for_class_templates.md
元の記述ではクラステンプレートの型推論を回避出来ていなかったため修正しました。
この修正は以下のpp.55--58を参考に記述しました。
[Class Template Argument Deduction - A New Abstraction - Zhihao Yuan - CppCon 2017](https://github.com/CppCon/CppCon2017/raw/master/Presentations/Class%20Template%20Argument%20Deduction%20-%20A%20New%20Abstraction/Class%20Template%20Argument%20Deduction%20-%20A%20New%20Abstraction%20-%20Zhihao%20Yuan%20-%20CppCon%202017.pdf)
> クラステンプレートの型推論を回避する例を修正

- implementation-status.md
ICXのラベルの一部分がC+となっていた部分を、おそらくC++であるべきと仮定して編集しました
> ICXのリンクラベルを修正しました

- lang/cpp20.md
- reference/memory/allocator.md
P0619R4 の次の記述によると、`allocator`クラスの`size_type`と`difference_type`はC++20で非推奨が取り消されているようです。
* https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0619r4.html#3.9
> Strong recommendation: Undeprecate std::allocator<T>::size_type and std::allocator<T>::difference_type, and remove the remaining deprecated parts from the C++20 standard: 
規格上でも`size_type`と`difference_type`は残っています。
* https://timsong-cpp.github.io/cppwp/default.allocator
なので、関連している記述を修正してみました。
`allocator`のリファレンスについては`size_type`と`difference_type`の説明に「C++17から非推奨、C++20で非推奨取り消し」などと書くべきかもしれませんが、わかりにくいかと思ったので「非推奨・削除の詳細」の節に説明を追加するようにしてみました。
> C++20でのallocatorクラスのsize_type型とdifference_type型の扱いを修正

- reference/random.md
`std::uniform_real_distribution<float>` などで生成した乱数を `double` で受け取っていたため修正しました。
> 生成した乱数のimplicit conversionを削除

- .github/workflows/meta_header_check.yml
- .github/workflows/script/meta_header_check.py
- #1203
[meta header]または[meta module]の指定ミスを検出するようにしてみました (指定ミスするとサイドバーが壊れる)。
自動検出できるなら指定する必要すらないのですが、、それは追々site_generatorを直します。
https://github.com/cpprefjp/site/commit/4f5d507d4e9830fee411f6f621b25ba1fc70cdb3
このコミットで[meta header]の指定ミスを修正する前の状態だと、以下のように出力されます。
```bash
[reference/ranges/from_range_t.md] invalid meta header "utility". You should specify "ranges" as meta header
```
module階層も同じように検出されます。
> 所属ヘッダの指定ミスを検出するCIタスクを追加

- working_style.md
型修飾のスタイルの一覧において、現在の実装ではプロポーショナルフォントで表示されますが、スペースの有無などが見にくいため、等幅フォントで表示できるコードブロックに記述するよう修正しました。
https://cpprefjp.github.io/working_style.html
> working_style: 型修飾のスタイルの一覧を等幅フォントで表示するよう修正

- implementation-status.md
https://software.intel.com/en-us/articles/c0x-features-supported-by-intel-c-compiler による
> impl(C++11,ICC): アライメント指定がサポートされたバージョンを追加

- reference/forward_list/forward_list/erase_after.md
forward_list::erase_afterの、"イテレート中に要素を削除する"サンプルコードについて、
条件一致した要素をerase_afterで削除した後、erase_afterの返り値をitに代入していますが、
この返り値は削除された要素の次の要素である"4"を指しているので、これをitに代入してしまうと、次のループで4のチェックが飛んでしまいます。(next == ls.end())
ここでは、erase_afterの返り値は単に無視すれば正しい動作になるかと思います。
わかり易さのために、`std::forward_list<int> ls = {3, 1, 1, 4};`に変更しています
- https://wandbox.org/permlink/0bxynAmBI80PrLOu
```cpp
#include <iostream>
#include <forward_list>
int main()
{
std::forward_list<int> ls = {3, 1, 1, 4};
// イテレート中に要素削除をするような場合には、
// 範囲for文は使用できない
for (auto it = ls.before_begin();;) {
auto next = std::next(it);
if (next == ls.end())
break;
// 条件一致した要素を削除する
if (*next == 1) {
// 削除された要素の次を指すイテレータが返される。
it = ls.erase_after(it);
}
// 要素削除をしない場合に、イテレータを進める
else {
++it;
}
}
for (const auto& x : ls) {
std::cout << x << std::endl;
}
}
```
```
3 …
```
> forward_list::erase_afterのサンプルコード修正

- .github/workflows/build.yml
- .github/workflows/code_qualify_check.yml
- .github/workflows/detect_forbidden_characters.yml
- .github/workflows/inner_link_check.yml
- .github/workflows/meta_header_check.yml
- .github/workflows/ngword_check.yml
- .github/workflows/outer_link_check.yml
CIの実行時に次のような警告が出ています。
>The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/setup-python@v1. For more info: 
>https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
actionsたちはnodejsで動くわけですがこのnodejsのバージョンアップ対応となります。
- checkout
- https://github.com/actions/checkout/blob/main/CHANGELOG.md
- setup-python
- https://github.com/actions/setup-python/releases
- cache
- https://github.com/actions/cache
- https://github.com/actions/cache/blob/v2/README.md
それぞれchange logを確認し、破壊的変更がないことを確認しました。
kunaiのビルドに、setup-nodeとかを使わずにいきなりnpmコマンドを呼び出していますが、
https://github.com/cpprefjp/site/blob/041ff2d5575a2b81f67f3265a126ee57cd54d4aa/.github/workflows/script/build.sh#L7-L11 …
> fix: CIのactionsをnode16以降対応に切り替える

- reference/memory/allocator.md
一応文面の確認はお願いしたさ(この辺の記述は 0e50afd3caa8220baa52f6e2f2926e3ddaeb2153 と 4f6b1a1d67f8fe632661a60095395af45dfe52ce なので @faithandbrave さんお願いします :bow:)
- `std::allocator_traits` で代替する話は非推奨・削除対象となったメンバ全般が対象となるのでそのように変更
- 一応メンバ関数については各ページで記載があるのですが，メンバ型は個別ページが無いのでここでまとめて記載
- そもそも `std::allocator<void>` が `rebind` を目的として使われることの説明が見当たらなかったので追加
- `std::allocator<void>` の特殊化の削除は `std::allocator<void>` の使用禁止を意味しないことを追記
- これはシンプルに[私が勘違いしていた](https://twitter.com/wx257osn2/status/1759530468125581498)ので同じような人が生まれないように
> std::allocatorの非推奨・削除についての説明を変更

- reference/memory/shared_ptr/const_pointer_cast.md
- reference/memory/shared_ptr/dynamic_pointer_cast.md
- reference/memory/shared_ptr/reinterpret_pointer_cast.md
- reference/memory/shared_ptr/static_pointer_cast.md
`shared_ptr`の`(const|static|dynamic|reinterpret)_pointer_cast`の解説では「動作未定義となる」という表現が使われています。
これは比較的耳にしない表現で、かつ他のページでは「未定義動作となる」の用例の方が多いため、そちらに統一しました。
他の候補として、「～という方法では、その動作は未定義となる」を考えましたが、冗長に感じたため「未定義動作となる」を選んでいます。
単にtypoとしてpushしようかと思いましたが、複数個所あったため一応ワンクッション置いた方が無難かと考えてpull reqにしています。問題なさそうでしたら、あるいは理由があってこの表現になっていた場合は、その旨お伝えください。
> typo: 動作未定義 -> 未定義動作

- reference/algorithm/ranges_copy.md
> docs: std::ranges::copyのサンプルコード内コメントの自明な修正

- reference/future/async.md
規格 (  [C++11](https://timsong-cpp.github.io/cppwp/n3337/futures.async#6) [C++20](https://timsong-cpp.github.io/cppwp/n4861/futures.async#7) ) を見る限り、`std::async` は `std::future_error` ではなく `std::system_error` を投げるように思えたので PR を出しました。
手元にぱっと試せる環境が無かったので、実際のコンパイラの動作は確認していません。
> fix bug: `std::async` は `std::future_error` ではなく `std::system_error` を投げる

- reference/string/stof.md
```cpp
#include <iostream>
#include <string>
int main()
{
// 10進法での変換
std::cout << "---- decimal point" << std::endl;
float a = std::stof("1.5"); // std::stof("1.5", nullptr);
std::cout << a << std::endl;
float aw = std::stof(L"1."); // std::stof(L"1.", nullptr);
std::cout << aw << std::endl;
// 指数表記の変換
std::cout << "---- base = 8" << std::endl;
float b = std::stof("0.5e3", nullptr);
std::cout << b << std::endl;
float bw = std::stof(L".25e3", nullptr);
std::cout << bw << std::endl;
// 16進法での変換
std::cout << "---- base = 16" << std::endl;
float c = std::stof("0x1.2P3", nullptr);
std::cout << c << std::endl;
float cw = std::stof(L"0x1.2P4", nullptr);
std::cout << cw << std::endl;
// 2番目の仮引数の使用例
std::cout << "---- use of idx parameter" << std::endl;
std::string es = "30.75%";
std::size_t ei; …
```
> [Update] gccの動作確認バージョンを追記

- reference/tuple/tuple_cat.md
C++20までの`std::tuple_cat`の要件が間違ってるようだったので修正してみました。
引数が左辺値参照であればコピー可能、そうでなければムーブ可能を要求する、というものですが、
左辺値参照であるかどうかを見るのはタプルの型で、コピーまたはムーブを要求するのはタプルの要素型なので、
元の記述は単純に間違っているように見えます。
> std::tuple_catの要件の修正

- reference/memory/shared_ptr/op_constructor.md
Add missing `noexcept` in `shared_ptr::shared_ptr(nullptr_t)`
close: #1249
長期間そのままになっていそうだったのでやってしまいました。
> Add missing `noexcept` in `shared_ptr`

- reference/map/multimap/merge.md
- reference/set/multiset/merge.md
一応gcc、clang、msvc、icc全てで確認しましたが、multiだと`source`の要素を全て挿入するようです。
> multisetとmultimapのmergeの説明の修正とICCのバージョンの追加

- reference/chrono/gps_clock.md
- reference/chrono/tai_clock.md
- 概要: TAI時計,GPS時計ではうるう秒補正が行われないことを明記
- うるう秒の扱い: "負のうるう秒"を考慮した表記に調整
- 例示: うるう秒の影響を追加
- gps_clockのうるう秒説明において"1970年"の意味を補足
> chrono/{tai,gps}_clock: クラス説明を増補

- implementation.md
https://github.com/cpprefjp/site/commit/2f771c9f5e2d693949cf280f03e7001203f86488#r150600641
上のコメントに基づき、表記と製品名との間に一貫性が無いので修正を提案します。
表記と製品名のどちらに合わせるかですが、`_MSC_VER` と `_MSC_FULL_VER` から推測するに製品名に合わせるのが妥当だと判断しました。
製品名は 17.0 系列ですので " Update 1" が無い表記にしています。
元のコミッターの @faithandbrave さんが良ければリアクションください。
そのリアクションに基づいて、私か@faithandbrave さんがマージすることを考えています。
> Visual Studio 2022 version 17.0.2の表記からUpdate 1を削除する

- reference/string_view/basic_string_view/op_sv.md
> string_view::op_sv : ヌル終端に関する説明がわかりにくかったので追記

- implementation-status.md
> P2564R3のMSVC対応を削除

- implementation.md
implementation.md の Microsoft Visual C++ / バージョンの表記の表の
`Visual Studio 2022` が関係する行の `version` を `Version` に置き換える案です。
経緯はこちらの[コメント欄](https://github.com/cpprefjp/site/commit/034c3678c310c91e851cea8a9383cf32af87ef4d)
> ただ、2022 の途中で version から Version に変わっているのは中途半端で変な感じがするので、取り敢えず 2022 は全部 Version にしませんか?
> cpprefjpとしてはその列にそれほど厳密性は求められていませんが (cpprefjp表記との対応がわかればいい)、ほかの人が編集するときに躊躇・混乱してしまうのが懸念されるところではありますね。
なので2022は全部「Version」にするのがいい気がします。
以前からダイアログ上では `Version` だったという追加の情報があったので、対応します。
---
このプルリクは `Version` 表記を推しているものではありません。
追加の変更が必要であれば、別コミットでしていただければと思ってます。
`バージョン` 表記で一括置換など、後から行うこともできます。
>  Visual Studio 2022についてversionをVersionに置き換える

- reference/list/list/splice.md
- Remove unnecessary `std::move` in `splice` of `std::list`
> fix: remove unnecessary `std::move` from `splice` of `std::list`

- reference/forward_list/forward_list/splice_after.md
Remove unnecessary `std::move` in splice of `std::forward_list`
> fix: remove unnecessary `std::move` in splice of `std::forward_list`

- reference/atomic/atomic/exchange.md
- reference/atomic/atomic_exchange.md
- reference/atomic/atomic_exchange_explicit.md
- reference/atomic/atomic_ref/exchange.md
> fix: use `replace with` instead of ` replace by`

- reference/barrier/barrier/arrive.md
- reference/barrier/barrier/arrive_and_drop.md
- reference/barrier/barrier/arrive_and_wait.md
- reference/barrier/barrier/wait.md
Code example in `std::barrier::arrive` was not runnable because `#include <mutex>` was missing to use `lock_guard`.
> fix: missing `#include <mutex>` in `std::barrier`

- index.md
画像の方はCreative Commonsの4.0を使っていましたが、画像以外の方は3.0になっていました。
3.0のページにも古いバージョンであることの注意文章がでているように、4.0へのアップデートで大きな問題はでないという認識です。
- https://creativecommons.org/licenses/by/3.0/
> Notice
This is an older version of this license. Compared to previous versions, the 4.0 versions of all CC licenses are [more user-friendly and more internationally robust ](https://creativecommons.org/version4/). If you are [licensing your own work ](https://creativecommons.org/choose/), we strongly recommend the use of the 4.0 license instead: [Deed - Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/deed.en)
> これはこのライセンスの古いバージョンです。以前のバージョンと比較して、すべてのCCライセンスの4.0バージョンはよりユーザーフレンドリーで、より国際的に堅牢です。ご自身の作品をライセンスする場合は、4.0ライセンスのご利用を強くお勧めします：Deed - Attribution 4.0 International
それと私のミスで申し訳ないのですが、Open …
> ライセンスのバージョンを更新

- lang/cpp20/deprecate_array_comparisons.md
> P1120R0: コメントの解説の誤植を修正

- reference/cstdio.md
- reference/cstdio/fopen_max.md
> Create page: fopen_max
