reference/unordered_map/unordered_map/op_at.md

fix output example

---

reference/istream/basic_istream/get.md

たぶんこれで合ってると思います(N3337，N4296あたりはこうなってました)

fix basic_istream::get interfaces

---

reference/random/chi_squared_distribution.md
reference/random/exponential_distribution.md
reference/random/extreme_value_distribution.md
reference/random/linear_congruential_engine.md
reference/random/lognormal_distribution.md
reference/random/normal_distribution.md
reference/random/weibull_distribution.md

* chi_squared_distribution
* exponential_distribution
* extreme_value_distribution
* linear_congruential_engine
* lognormal_distribution
* normal_distribution
* weibull_distribution

Fix formulae of PDFs of <random>

---

reference/utility.md
reference/utility/as_const.md

気が早いですがC++17(仮)のas_constを作成してみました。
C++17(仮)で追加されるライブラリのページを作るのは時期尚早でしょうか？
また私は初めてページの新規作成をしたので、初回ということでチェックをお願いします 。問題なければ次回以降は直接pushしようと思います。

as_constを追加

---

reference/cmath.md
reference/cmath/erf.md
reference/cmath/erfc.md
reference/cmath/lgamma.md
reference/cmath/tgamma.md

サポートされ始めた処理系が分からなかったので，ご存じの方は加筆してください

erf, erfc, lgamma, tgamma を追加 (fix #377)

---

reference/unordered_map/unordered_map/reserve.md
reference/unordered_map/unordered_multimap/reserve.md
reference/unordered_set/unordered_multiset/reserve.md
reference/unordered_set/unordered_set/reserve.md
reference/vector/pop_back.md

いくつかのリンクで、リンクの文字列とリンク先が食い違っている箇所がありましたので修正です

Fix link target

---

reference/random/random_device.md

* インクルードガード追加
* 可読性向上のため空行を追加，変数を整理

random_device: workaround 改善 (#458)

---

reference/cstddef/size_t.md

size_tの説明を最新の規格に合わせた

---

implementation-status.md

MSVCについて言語機能の実装状況を修正

---

reference/iomanip.md
reference/iomanip/resetiosflags.md
reference/iomanip/setbase.md
reference/iomanip/setfill.md
reference/iomanip/setiosflags.md
reference/iomanip/setw.md
reference/ios/basic_ios/copyfmt.md
reference/ios/basic_ios/fill.md
reference/ios/defaultfloat.md
reference/ios/ios_base/precision.md
reference/ios/ios_base/width.md
reference/ios/left.md
reference/ostream/basic_ostream/op_ostream_free.md
reference/valarray/gslice_array.md

影響がそれなりに広いのでPRにしました。
特に問題がなさそうならセルフマージします。

iomanipにマニピュレータの説明を追加

---

lang/cpp17/constexpr_lambda.md

constexpr ラムダのサンプルコード修正

---

reference/regex/regex_iterator.md

regerx_iteretor sampleの修正

---

lang/cpp17/replacement_of_class_objects_containing_reference_members.md

Task の、「参照メンバをもつクラスの置き換え」をやりました！

 create file for 参照メンバをもつクラスの置き換え #411

---

international-standard.md

ref:
- #644
とりあえず変更してみました。reviewお願いします。
最終国際規格案と参照する規格案は両方あったほうが良いのではないかと思いそうしてみました。

feat(IS): add link to timsong-cpp.github.io

---

editors_doc/class_template_page.md
editors_doc/function_template_page.md
editors_doc/type-type_template_page.md
reference/concepts.md
reference/concepts/Callable.md
reference/concepts/CopyAssignable.md
reference/concepts/CopyConstructible.md
reference/concepts/DefaultConstructible.md
reference/concepts/Destructible.md
reference/concepts/EqualityComparable.md
reference/concepts/Invoke.md
reference/concepts/LessThanComparable.md
reference/concepts/MoveAssignable.md
reference/concepts/MoveConstructible.md
reference/concepts/Swappable.md
reference/concepts/ValueSwappable.md

https://github.com/cpprefjp/site_generator/pull/66

コンセプトカテゴリを追加

---

reference/string_view/basic_string_view.md

Fix typo in basic_string_view

---

lang/cpp17/if_constexpr.md
lang/cpp20/function_templates_with_auto_parameters.md

サイトを利用中に発見したヘッダー抜けやtypoの修正です
ただのtypo修正ですが久しぶりに見た&cpp20年の対応作業などが走っていそうなのでプルリクで投げておきます

ヘッダー抜けやtypoの修正

---

implementation-status.md

判る範囲ではありますが、Visual Studio 2019 Update5の情報と気が付いた個所を記載しました
あとSTLの `Changelog` が公開されているので、そのリンクを追加しています
お手すきの時にでも確認をお願いします
（Update情報は網羅までは出来てないです）

Updated MSVC info for 2019 16.5

---

reference/memory/enable_shared_from_this.md

Fix typo in reference/memory/enable_shared_from_this.md

---

.github/workflows/script/link_check.py

#802
404になったページがたくさんあったので、これを修正してからマージします。
```
faithandbrave$ python3 .github/workflows/script/link_check.py --check-outer-link
URL https://wiki.apache.org/stdcxx/C++0xCompilerSupport not found. 404 from:['implementation-status.md']
URL http://www.unicode.org/%7Easmus/stdc-utf-16.txt not found. 404 from:['lang/cpp20/char8_t.md']
URL http://zakkas783.tumblr.com/post/25490513807/constant-initialization not found. 404 from:['lang/cpp11/constexpr.md', 'reference/mutex/mutex/op_constructor.md']
URL https://gcc.gnu.org/onlinedocs/gcc/Namespace-Association.html not found. 404 from:['lang/cpp11/inline_namespaces.md']
URL https://qiita.com/loppta/items/69a0ed56ff12d2c0261c not found. 404 from:['lang/cpp11/range_based_for.md']
URL http://courses.cs.vt.edu/professionalism/Therac_25/Therac_3.html not …
```

外部リンクチェック : サイトのトップページの存在チェックしかされていなかったので、完全URLで存在チェックするよう修正

---

reference/list/list/unique.md

C++03 -> C++20

---

reference/node_handle.md
reference/node_handle/node_handle.md
reference/node_handle/node_handle/empty.md
reference/node_handle/node_handle/get_allocator.md
reference/node_handle/node_handle/key.md
reference/node_handle/node_handle/mapped.md
reference/node_handle/node_handle/op_assign.md
reference/node_handle/node_handle/op_bool.md
reference/node_handle/node_handle/op_constructor.md
reference/node_handle/node_handle/op_destructor.md
reference/node_handle/node_handle/swap.md
reference/node_handle/node_handle/swap_free.md
reference/node_handle/node_handle/value.md

ローカルで動かしてみて特にサイドバーに問題無かったので、 f7d9e6e8736e404c5d0c1e96f1f48c63b05aa64f を cherry-pick しました

node_handle : headerではなくcategoryにした

---

.github/workflows/detect_forbidden_characters.yml

https://github.com/BurntSushi/ripgrep/releases/tag/13.0.0

fix(ci): ripgrep 13.0.0

---

lang/cpp17/if_constexpr.md

ページ冒頭のサンプルコードが if constexpr ではなく if constepxr になっていましたので修正PRを送らせていただきます。

constexpr if のタイポ修正

---

.github/workflows/script/link_check.py

RのTipsサイトをリンクチェックから除外

---

reference/filesystem.md

fix typo s/ディレクト内の/ディレクトリ内の/

---

reference/concepts/integral.md

integralのソースコード例に誤植がありそうだったのでpull requestを送ります。
初めてpull requestを送るので何か間違えていたらスミマセン…

integralのソースコード修正

---

reference/map/map.md
reference/map/map/op_less_equal.md
reference/map/multimap.md
reference/map/multimap/op_equal.md
reference/map/multimap/op_greater.md
reference/map/multimap/op_greater_equal.md
reference/map/multimap/op_less.md
reference/map/multimap/op_less_equal.md
reference/map/multimap/op_not_equal.md

mapとmultimapのoperator<=のmdファイルがなかったので追加。

add missing files

---

lang/cpp23.md

タイポを見つけたので修正しました。
リンク先の URL や記述内容にタイポはありませんでした。

fix typo: algined -> aligned

---

reference/algorithm/ranges_shift_left.md
reference/algorithm/ranges_shift_right.md
reference/algorithm/shift_left.md
reference/algorithm/shift_right.md

shift_left/shift_rightで負数を指定可能と読める記述の修正

---

lang/cpp20/deprecate_pod.md

typo を修正: "スタンダードレイアウト型型" -> "スタンダードレイアウト型"

---

reference/algorithm.md

サンプルコードが typo のためコンパイルが通らなかったので修正しました

fix typo in algorithm's sample code

---

reference/new/op_new.md

サンプルコードが typo のためコンパイルが通らなかったので修正しました

fix typo in op_new's sample code

---

lang/cpp11/pragma_operator.md

恐らくミスと思われたのでその修正です。勘違いでしたらすみません。

fix: C++11/Pragma演算子 の項のサンプルコード中のコメントの修正

---

reference/string/stoi.md
reference/string/stol.md

Fix: some typo

---

reference/memory/unique_ptr/op_constructor.md

`std::unique_ptr`のコンストラクタのページに自作デリータを使った例を追加してみました。
念の為、Valgrindでメモリリークが無いことを確認してます。

std::unique_ptrに自作デリータの使用例を追加

---

reference/utility.md

utility.md 内の見出しのミスを修正。
経緯：issue https://github.com/cpprefjp/site/issues/1302

見出しを修正（"列挙型" -> "到達しない表明"）

---

.github/workflows/script/display_error_check.py
reference/algorithm/lexicographical_compare_three_way.md
reference/iterator/iterator_traits.md
reference/iterator/reverse_iterator/op_arrow.md
reference/string/basic_string/append.md
reference/string/basic_string/assign.md
reference/string/basic_string/compare.md
reference/string/basic_string/insert.md
reference/string/basic_string/op_assign.md
reference/string/basic_string/op_plus.md
reference/string/basic_string/op_plus_assign.md
reference/string/basic_string/replace.md

- #1367
`*`ではじまる箇条書きのチェックが漏れていました

表示崩れチェックCI : `*`ではじまる箇条書きをチェック

---

reference/sstream/basic_istringstream.md

istringstreamのためのサンプルコードを作成しました。
よろしくおねがいします。

new sample code for istringstream

---

reference/vector/vector/insert.md

何となく見ていて気になったので初PR
consrexpr→constexpr

typo修正：vector/insert

---

lang/cpp26/allowing_exception_throwing_in_constant-evaluation.md
reference/expected/bad_expected_access/error.md
reference/expected/bad_expected_access/op_constructor.md
reference/expected/bad_expected_access/what.md
reference/format/format_error.md
reference/format/format_error/op_assign.md
reference/format/format_error/op_constructor.md
reference/format/format_error/op_destructor.md
reference/format/format_error/what.md
reference/optional/bad_optional_access.md
reference/optional/bad_optional_access/op_assign.md
reference/optional/bad_optional_access/op_constructor.md
reference/optional/bad_optional_access/op_destructor.md
reference/optional/bad_optional_access/what.md
reference/stdexcept.md
reference/variant/bad_variant_access.md
reference/variant/bad_variant_access/op_assign.md
reference/variant/bad_variant_access/op_constructor.md
reference/variant/bad_variant_access/op_destructor.md
reference/variant/bad_variant_access/what.md

stdexcept関係のconstexpr対応

---

.gitignore

- Add `.gitignore` file to exclude `.DS_Store`, editor config files and more

chore: add `.gitignore` file

---

reference/cstdlib/mb_cur_max.md

すみません。
新しく作成してしましました。
ご指摘頂いた箇所は修正いたしました。

`namespace std`の削除、表記の変更

---

.github/workflows/script/check.py
.github/workflows/script/code_qualify_check.py
.github/workflows/script/defined_word_check.py
.github/workflows/script/display_error_check.py
.github/workflows/script/global_qualify_check.py
.github/workflows/script/link_check.py
.github/workflows/script/meta_header_check.py
.github/workflows/script/ngword_check.py
README.md

これだけ実行すれば、Pull RequestのCIと同等のチェックがローカルで確認できるようにしました。
```sh
python3 .github/workflows/script/check.py
```
これで、masterブランチ上での作業がしやすくなることを期待します。
シェルスクリプトにしてないのは、Windows向けなら.cmdファイルを用意するとかが二重管理になって嫌なので、Pythonだけ入っていれば実行できるようにしています。

Pull RequestのCIと同等のチェックをローカルで一度に実行するスクリプトを追加
